---
- name: Wednesday challenge
  hosts: looneytunes 
  connection: ssh
  gather_facts: yes   

  tasks:
    - name: create the challenge/ folder
      file:
        state: directory
        path: ~/challenge
    - name: Access the Website and make sure the URL is live
      uri:
        method: GET 
        url: https://raw.githubusercontent.com/csfeeser/ansible_essentials/main/data/downloadme.txt
        status_code: 200 
        return_content: true
      register: validateurl   
    - name: "INFO: HTTP Response for the URL"
      debug:
        var: validateurl.msg

